// server/src/controllers/calendar.controller.ts
// Powers the Home board's Calendar screen — one outfit per date,
// past (log what you wore) or future (plan ahead), plus the
// "Outfit of the Day" snap/wrap confirmation flow.

import { Request, Response } from 'express';
import { randomUUID } from 'crypto';
import {
  setCalendarEntry, getCalendarEntry, listCalendarEntriesForMonth, deleteCalendarEntry,
  listWardrobeItems, createOutfit, getOutfit, getWardrobeItemsByIds,
} from '../services/mongodb.service';
import { pickOutfitItems } from '../services/aiStylist.service';
import { Outfit } from '../types/domain';

function requireUser(req: Request, res: Response): string | null {
  const userId = req.auth?.userId;
  if (!userId) {
    res.status(401).json({ error: 'Not authenticated' });
    return null;
  }
  return userId;
}

function todayISO(): string {
  return new Date().toISOString().slice(0, 10);
}

// GET /api/calendar?month=YYYY-MM
export async function listMonth(req: Request, res: Response) {
  const userId = requireUser(req, res); if (!userId) return;
  const month = (req.query.month as string) || new Date().toISOString().slice(0, 7);
  if (!/^\d{4}-\d{2}$/.test(month)) return res.status(400).json({ error: 'month must be YYYY-MM' });
  const entries = await listCalendarEntriesForMonth(userId, month);
  res.json(entries);
}

// GET /api/calendar/:date   (date = YYYY-MM-DD)
export async function getDay(req: Request, res: Response) {
  const userId = requireUser(req, res); if (!userId) return;
  const entry = await getCalendarEntry(userId, req.params.date);
  res.json(entry);
}

// PUT /api/calendar/:date   body: { outfitId, note? }
export async function setDay(req: Request, res: Response) {
  const userId = requireUser(req, res); if (!userId) return;
  const { outfitId, note } = req.body as { outfitId: string; note?: string };
  if (!outfitId) return res.status(400).json({ error: 'outfitId is required' });
  const entry = await setCalendarEntry(userId, req.params.date, outfitId, note);
  res.json(entry);
}

// DELETE /api/calendar/:date
export async function removeDay(req: Request, res: Response) {
  const userId = requireUser(req, res); if (!userId) return;
  await deleteCalendarEntry(userId, req.params.date);
  res.json({ ok: true });
}

// GET /api/calendar/today/outfit — powers the Home banner's single-tap
// "Outfit of the Day" button. If today already has an assigned outfit
// (set manually via the Calendar screen, or generated by a previous
// call to this same endpoint), returns that one — doesn't regenerate
// a new outfit every time you tap it, same outfit stays "the" one for
// today until you change it. If nothing's assigned yet, generates one
// fresh (reusing the same picking logic as regular outfit generation,
// no specific occasion/mood — a sensible casual daily default), saves
// it, and assigns it to today automatically so it's consistent for
// the rest of the day.
//
// Returns the outfit's full item objects (not just IDs) so the client
// can read actual colors immediately — that's what drives the banner
// matching its background to the outfit's dominant color, without a
// second round-trip to resolve item IDs into item data.
export async function getOrGenerateTodayOutfit(req: Request, res: Response) {
  const userId = requireUser(req, res); if (!userId) return;
  const date = todayISO();

  const existingEntry = await getCalendarEntry(userId, date);
  if (existingEntry?.outfitId) {
    const outfit = await getOutfit(userId, existingEntry.outfitId);
    if (outfit) {
      const items = await getWardrobeItemsByIds(userId, outfit.itemIds ?? []);
      return res.json({ outfit, items, isNew: false });
    }
  }

  const closet = await listWardrobeItems(userId);
  if (closet.length === 0) {
    return res.status(200).json({ outfit: null, items: [], isNew: false, message: 'Add some items to your closet first — nothing to build an outfit from yet.' });
  }

  const pickedItems = pickOutfitItems(closet, null, null, null);
  if (pickedItems.length === 0) {
    return res.status(200).json({ outfit: null, items: [], isNew: false, message: "Couldn't put together an outfit from what's in your closet yet — try adding a few more pieces." });
  }

  const now = Date.now();
  const outfit: Outfit = {
    id: randomUUID(), userId, sessionId: null,
    name: 'Outfit of the Day', description: null,
    itemIdsBySlot: { tops: [], pants: [], shoes: [], bags: [], other: pickedItems.map((i) => i.id) },
    itemIds: pickedItems.map((i) => i.id),
    category: null, customCategories: [], season: null, rating: null, aesthetic: null,
    brand: null, price: null, size: null, material: null,
    story: null, matchScore: null, source: 'ai_generated', isFavorite: false, deletedAt: null,
    createdAt: now, updatedAt: now,
  };
  await createOutfit(outfit);
  await setCalendarEntry(userId, date, outfit.id);

  res.json({ outfit, items: pickedItems, isNew: true });
}
